import type { Metadata } from "next";

import { Footer } from "@/components/layout/Footer";
import { LegalPage } from "@/components/layout/LegalPage";
import { Navbar } from "@/components/layout/Navbar";
import { LOGIN_ROUTE, POST_LOGIN_ROUTE } from "@/lib/auth";
import { getCurrentUser } from "@/lib/insforge-server";

export const metadata: Metadata = {
  title: "Privacy Policy — JobMax",
};

const SECTIONS = [
  {
    heading: "Information we collect",
    paragraphs: [
      "When you create an account we collect your email address and basic account details from the sign-in provider you choose. When you build your profile we store the information you enter — your professional details, skills, work history, and preferences — along with any resume you upload.",
      "As you use JobMax, we also record activity generated by the product itself, such as job searches you run, jobs saved to your list, and company research you request.",
    ],
  },
  {
    heading: "How we use your information",
    paragraphs: [
      "Your profile and resume are used to find, score, and present job matches to you, and to prepare application materials you explicitly request. Activity data powers your own dashboard — counts, recent activity, and trends are shown to you and to no one else.",
      "We do not sell your personal information, and we do not use it for advertising.",
    ],
  },
  {
    heading: "Third-party services",
    paragraphs: [
      "JobMax is built on trusted service providers that process data on our behalf: authentication, database, and file storage; job listings retrieval; AI services that score matches and generate documents from the information you provide; browser automation used for company research; and product analytics that help us understand how the app is used.",
      "Each provider receives only what it needs to perform its function. Job applications always happen on the employer's own site — JobMax never submits applications on your behalf.",
    ],
  },
  {
    heading: "Cookies",
    paragraphs: [
      "We use cookies to keep you signed in. These are essential to the service and are not used to track you across other sites.",
    ],
  },
  {
    heading: "Data retention and your rights",
    paragraphs: [
      "Your data remains yours. You can update your profile at any time, replace or remove your uploaded resume, and request deletion of your account and its data by contacting us. When your account is deleted, your profile, saved jobs, and stored files are removed from our systems.",
    ],
  },
  {
    heading: "Security",
    paragraphs: [
      "We protect your data with industry-standard measures, including encrypted connections and access controls that scope every piece of data to your account. No method of storage or transmission is completely secure, but we work to protect your information appropriately.",
    ],
  },
  {
    heading: "Changes to this policy",
    paragraphs: [
      "We may update this policy from time to time. When we do, we will revise the date at the top of this page. Continued use of JobMax after changes take effect constitutes acceptance of the revised policy.",
    ],
  },
  {
    heading: "Contact",
    paragraphs: [
      "Questions about this policy or your data can be sent to support@jobmax.app.",
    ],
  },
];

export default async function PrivacyPage() {
  const user = await getCurrentUser();

  return (
    <>
      <Navbar
        ctaHref={user ? POST_LOGIN_ROUTE : LOGIN_ROUTE}
        ctaLabel={user ? "Go to dashboard" : "Start for free"}
      />
      <LegalPage
        title="Privacy Policy"
        lastUpdated="August 3, 2026"
        intro="This policy explains what information JobMax collects, how it is used, and the choices you have. It applies to everything you do on JobMax — from building your profile to searching for jobs and researching companies."
        sections={SECTIONS}
      />
      <Footer />
    </>
  );
}
